mazarini_rescue_debootstrap:
  storage_groups:
    # Groupe principal pour le système
    - disk_model: 
        type: "nvme"
        sector_size: 4096
        start_sector: 256
        end_sector: 109887240
      disks: 
        - {number: 1, device: "/dev/nvme0n1"}
        - {number: 2, device: "/dev/nvme1n1"}
      partitions:
        - { number: 1, type: "efi",        size: 66560,     label: "EFI" }   # 260 MiB
        - { number: 2, type: "btrfs",      size: 107723273, label: "RPOOL"}  # 421 GiB
        - { number: 3, type: "linux-swap", size: 2097152,   label: "SWAP" }  # 8 GiB
